# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    environment:
      IMAGE_NAME: ugmarket

    working_directory: ~/ugmarket

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
            echo 'export DB_HOST=$DB_HOST' >> $BASH_ENV
            echo 'export DB_PORT=$DB_PORT' >> $BASH_ENV
            echo 'export DB_NAME=$DB_NAME' >> $BASH_ENV
            echo 'export DB_USERNAME=$DB_USERNAME' >> $BASH_ENV
            echo 'export DB_PASSWORD=$DB_PASSWORD' >> $BASH_ENV
            source $BASH_ENV

      - run: npm install

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/$IMAGE_NAME .

      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$TAG .
            docker tag $IMAGE_NAME:$TAG
            #$IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME::$TAG
            #docker push $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1

      - run:
          name: Deploy Code
          command: ./script/do_deploy.sh
 